#!/usr/bin/env python3
import os
import datetime
import time
import logging
import random

import pysftp


def main():
    root_logger = logging.getLogger('')
    root_logger.setLevel(logging.INFO)

    cnopts = pysftp.CnOpts()
    cnopts.hostkeys = None

    storage_path = '.'

    interval = datetime.timedelta(seconds=30)
    next_run = datetime.datetime.now()

    with pysftp.Connection('localhost', port=2222, username='cortex', password='password', cnopts=cnopts) as sftp:
        while True:
            now = datetime.datetime.now()

            if now > next_run:
                logging.info("Data generation start")

                generate_data(sftp, storage_path, next_run)

                next_run += interval

                logging.info(f"Done, waiting for next run at {next_run}")

            time.sleep(100)


def send_file(sftp, storage_path, file_name, generate_lines):
    file_path = os.path.join(storage_path, file_name)

    generate_file(file_path, generate_lines)

    sftp.put(file_path, file_name)

    os.remove(file_path)


def mkdir_all(sftp, path):
    head, tail = os.path.split(path)

    if not sftp.isdir(head):
        mkdir_all(sftp, head)
    else:
        sftp.mkdir(path)


def check_path(sftp, path):
    if not sftp.isdir(path):
        mkdir_all(sftp, path)


def generate_data(sftp, storage_path, timestamp):
    check_path(sftp, 'upload/blue/1')

    with sftp.cd('upload/blue/1'):
        for i in range(100):
            file_name = f'test_blue_{i}_{timestamp:%Y%m%d:%H:%M:%S}.xml'

            send_file(sftp, storage_path, file_name, line_generator(1000, 30))

    check_path(sftp, 'upload/blue/2')

    with sftp.cd('upload/blue/2'):
        for i in range(1000):
            file_name = f'test_blue_{i}_{timestamp:%Y%m%d:%H:%M:%S}.xml'

            send_file(sftp, storage_path, file_name, line_generator(50, 8))

    check_path(sftp, 'upload/red')

    with sftp.cd('upload/red'):
        generated_files = []

        for i in range(1000):
            file_name = f'test_red_{i}_{timestamp:%Y%m%d:%H:%M:%S}.xml'

            send_file(sftp, storage_path, file_name, line_generator(50, 8))
            generated_files.append(file_name)

        for file_name in generated_files:
            try:
                sftp.remove(file_name)
                logging.info("Removed {}".format(file_name))
            except IOError as e:
                pass


def generate_file(file_path, generate_lines):
    with open(file_path, 'w') as out_file:
        out_file.writelines(generate_lines())

    logging.info(f"Written {file_path}")


def line_generator(num_lines, num_columns):
    def generate_lines():
        yield ','.join(f'col_{i}' for i in range(num_columns)) + '\n'

        for i in range(num_lines):
            yield ','.join(str(random.random() * i) for i in range(num_columns)) + '\n'

    return generate_lines


if __name__ == '__main__':
    main()
