variables:
  POSTGRES_HOST_AUTH_METHOD: trust
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

image: "harbor.hendrikx-itc.nl/1optic/rust-ci:1.75.0"

stages:
  - build

publish-cortex-dispatcher-deb:
  stage: build
  artifacts:
    paths:
      - "target/**/*.deb"
  before_script:
    - echo "$CACERT" > /ca.crt
  script:
    - cargo deb -p cortex-dispatcher --target=x86_64-unknown-linux-musl
    - |
      curl \
      --fail \
      --cacert "/ca.crt" \
      -u "${REPO_USERNAME}:${REPO_PASSWORD}" \
      -H "Content-Type: multipart/form-data" \
      --data-binary "@./target/x86_64-unknown-linux-musl/debian/cortex-dispatcher_${CI_COMMIT_TAG}-1_amd64.deb" \
      "$REPO_URL"
  rules:
    - if: $CI_COMMIT_TAG
